"""Velocity presentation view models and pure transforms."""

from chappy.presentation.velocity.display_range import (
    MAX_VELOCITY_DISPLAY_HALF_WIDTH_KMS,
    MIN_VELOCITY_DISPLAY_HALF_WIDTH_KMS,
    VelocityAnalysisBounds,
    VelocityDisplayHalfWidth,
    VelocityDisplayRangeSource,
    VelocityDisplayRangeState,
    VelocityDisplayScopeKey,
    clear,
    commit_manual,
    derive_velocity_display_half_width,
    fit_view_to_analysis_ranges,
    initialize,
    switch_scope,
)
from chappy.presentation.velocity.events import (
    VelocityComponentCreateRequest,
    VelocityContextMenuRequest,
    VelocityDragComplete,
    VelocityDragRequest,
    VelocityDragUpdate,
    VelocitySelectionCreateRequest,
)
from chappy.presentation.velocity.grid_presenter import (
    MAX_VELOCITY_SUBPLOTS,
    VelocityGridPage,
    VelocityGridPresenter,
    compute_velocity_grid_capacity,
    compute_velocity_grid_shape,
)
from chappy.presentation.velocity.overlay_info import VelocityOverlayInfo
from chappy.presentation.velocity.plot_presenter import (
    VelocityPaginationState,
    VelocityVisibleSliceState,
    build_velocity_pagination_state,
    build_visible_slice_states,
    compute_auto_flux_range,
)
from chappy.presentation.velocity.selection_model import (
    normalize_velocity_slices,
    preserve_velocity_slice_selection,
    resolve_velocity_slice_selection,
    selected_velocity_slices,
    toggle_velocity_slice_selection,
)
from chappy.presentation.velocity.slice_render_builder import (
    VelocityComponentProfileCurve,
    VelocityCurveSources,
    VelocitySliceRenderData,
    VelocitySliceRenderFailure,
    VelocitySliceRenderFailureReason,
    VelocitySliceRenderInput,
    build_velocity_slice_render_input,
    build_velocity_slot_render_input,
)
from chappy.presentation.velocity.transforms import compute_residual, compute_velocity_slice
from chappy.presentation.velocity.view_model import (
    VelocityCenterLineInfo,
    VelocityComponentInfo,
    VelocityComponentProfile,
    VelocityMaskRegionInfo,
    VelocitySliceInfo,
    VelocitySliceParams,
    VelocitySpectrumData,
    VelocityUnit,
    VelocityViewData,
    build_velocity_view_data,
)

__all__ = [
    "MAX_VELOCITY_DISPLAY_HALF_WIDTH_KMS",
    "MAX_VELOCITY_SUBPLOTS",
    "MIN_VELOCITY_DISPLAY_HALF_WIDTH_KMS",
    "VelocityAnalysisBounds",
    "VelocityCenterLineInfo",
    "VelocityComponentCreateRequest",
    "VelocityComponentInfo",
    "VelocityComponentProfile",
    "VelocityComponentProfileCurve",
    "VelocityContextMenuRequest",
    "VelocityCurveSources",
    "VelocityDisplayHalfWidth",
    "VelocityDisplayRangeSource",
    "VelocityDisplayRangeState",
    "VelocityDisplayScopeKey",
    "VelocityDragComplete",
    "VelocityDragRequest",
    "VelocityDragUpdate",
    "VelocityGridPage",
    "VelocityGridPresenter",
    "VelocityMaskRegionInfo",
    "VelocityOverlayInfo",
    "VelocityPaginationState",
    "VelocitySelectionCreateRequest",
    "VelocitySliceInfo",
    "VelocitySliceParams",
    "VelocitySliceRenderData",
    "VelocitySliceRenderFailure",
    "VelocitySliceRenderFailureReason",
    "VelocitySliceRenderInput",
    "VelocitySpectrumData",
    "VelocityUnit",
    "VelocityViewData",
    "VelocityVisibleSliceState",
    "build_velocity_pagination_state",
    "build_velocity_slice_render_input",
    "build_velocity_slot_render_input",
    "build_velocity_view_data",
    "build_visible_slice_states",
    "clear",
    "commit_manual",
    "compute_auto_flux_range",
    "compute_residual",
    "compute_velocity_grid_capacity",
    "compute_velocity_grid_shape",
    "compute_velocity_slice",
    "derive_velocity_display_half_width",
    "fit_view_to_analysis_ranges",
    "initialize",
    "normalize_velocity_slices",
    "preserve_velocity_slice_selection",
    "resolve_velocity_slice_selection",
    "selected_velocity_slices",
    "switch_scope",
    "toggle_velocity_slice_selection",
]
