name = "qso_absorbers"

description = "Quasar absorber lines spanning hydrogen and common metals"

species = [
  "H I",
  "D I",
  "He I",
  "He II",
  "Be II",
  "B II",
  "C I",
  "C II",
  "C III",
  "C IV",
  "N I",
  "N II",
  "N III",
  "N V",
  "O I",
  "O II",
  "O III",
  "O IV",
  "O VI",
  "Ne VIII",
  "Na I",
  "Mg I",
  "Mg II",
  "Mg X",
  "Al I",
  "Al II",
  "Al III",
  "Si I",
  "Si II",
  "Si III",
  "Si IV",
  "P I",
  "P II",
  "P III",
  "P IV",
  "P V",
  "S I",
  "S II",
  "S III",
  "S IV",
  "S V",
  "S VI",
  "Cl I",
  "Ar I",
  "Ca I",
  "Ca II",
  "Ti II",
  "Ti III",
  "Cr II",
  "Mn II",
  "Fe I",
  "Fe II",
  "Fe III",
  "Co II",
  "Ni I",
  "Ni II",
  "Cu II",
  "Zn II",
  "Ge II",
  "Ga II",
]

[[filters.profiles]]
name = "hydrogen"
elements = ["H", "D"]
max_ei_ev = 12
min_f = 0.00001

[[filters.profiles]]
name = "other"
max_ei_ev = 0.86
min_f = 0.0001
elements = [
  "He",
  "Be",
  "B",
  "C",
  "N",
  "O",
  "Ne",
  "Na",
  "Mg",
  "Al",
  "Si",
  "P",
  "S",
  "Cl",
  "Ar",
  "Ca",
  "Ti",
  "Cr",
  "Mn",
  "Fe",
  "Co",
  "Ni",
  "Cu",
  "Zn",
  "Ga",
  "Ge",
]
