"""Presentation-layer interaction contracts."""

from chappy.presentation.interaction.interaction_contracts import (
    AbsorberDragContext,
    ContinuumContext,
    ContinuumOperationType,
    Coordinate,
    InteractionChannel,
    InteractionEvent,
    InteractionEventKind,
    InteractionId,
    InteractionOutcome,
    InteractionPhase,
    InteractionStateSnapshot,
    MaskSelectionContext,
    MaskSelectionRequest,
    RectZoomBounds,
    RectZoomContext,
    ValidationError,
    VelocityContext,
)

__all__ = [
    "AbsorberDragContext",
    "ContinuumContext",
    "ContinuumOperationType",
    "Coordinate",
    "InteractionChannel",
    "InteractionEvent",
    "InteractionEventKind",
    "InteractionId",
    "InteractionOutcome",
    "InteractionPhase",
    "InteractionStateSnapshot",
    "MaskSelectionContext",
    "MaskSelectionRequest",
    "RectZoomBounds",
    "RectZoomContext",
    "ValidationError",
    "VelocityContext",
]
